# CMS

[Target]
profile-desc=色彩管理
icc-profile=""
icc-profile-auto=no
target-prim=bt.2020
target-gamut=display-p3
# target-peak=1000
target-contrast=inf
# target-colorspace-hint=no
target-colorspace-hint-mode=target
# target-colorspace-hint-strict=no
# dither-depth=10
# dither=error-diffusion
# error-diffusion=floyd-steinberg
deband=no

# HDR
hdr-compute-peak=auto
hdr-peak-percentile=99.995
# hdr-peak-decay-rate=20.0
# hdr-scene-threshold-low=1.0
# hdr-scene-threshold-high=3.0
hdr-contrast-recovery=0.30
# hdr-contrast-smoothness=3.50
allow-delayed-peak-detect=no
# sub-hdr-peak=100
image-subs-hdr-peak=sdr
inverse-tone-mapping=no

[SDR]
profile-desc=SDR 配置
profile-cond=get("video-params/gamma") == "bt.1886" and not get("inverse-tone-mapping")
profile-restore=copy
target-colorspace-hint=no

[SDR-Gamut]
profile-desc=SDR 色域映射调整
profile-cond=get("video-params/primaries") ~= "bt.709" and get("video-params/gamma") == "bt.1886"
profile-restore=copy-equal
gamut-mapping-mode=clip

[HDR]
profile-desc=HDR 配置
profile-cond=get("video-params/max-luma") > 203
profile-restore=copy
target-colorspace-hint=auto
deband=no

[HDR-Pass]
profile-desc=HDR 直通
profile-cond=get("video-params/max-luma") > 203 and get("video-target-params/max-luma") > 203
profile-restore=copy
target-prim=auto
target-gamut=auto
target-trc=auto
# target-peak=auto
# target-contrast=auto

[HDR-Peak]
profile-desc=HDR 峰值亮度调整
profile-cond=get("video-params/avg-pq-y") < 0.21
profile-restore=copy
hdr-peak-percentile=99.8

[HDR-2390]
profile-desc=bt.2390 映射调整
profile-cond=p.tone_mapping == "bt.2390"
profile-restore=copy-equal
tone-mapping-param=2.0
