# autoload
disabled=no
additional_image_exts=jfif
additional_video_exts=asf,f4v,rm,ts,vob
additional_audio_exts=dsf,spx
same_type=yes
directory_mode=ignore
# ignore_hidden=no
# ignore_patterns=^~,^bak-,%.bak$
