# OSC
# visibility=auto
# showwindowed=yes
# showfullscreen=yes
# layout=bottombar
# seekbarstyle=bar
title=${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename}}
# windowcontrols_title=${?pause==yes:⏸️}${?mute==yes:🔇}${?ontop==yes:📌}${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename}}
# chapter_fmt=Chapter: %s
# timetotal=yes
# timems=yes
unicodeminus=yes
# tick_delay=1/60
# tick_delay_follow_display_fps=yes
# greenandgrumpy=yes
