# ytdl
try_ytdl_first=yes
exclude=%.avi$|%.flac$|%.flv$|%.mp3$|%.m3u$|%.m3u8$|%.m4a$|%.m4v$|%.mkv$|%.mp4$|%.ts$|%.vob$|%.wav$|%.webm$|%.wmv$
# include=^%w+%.youtube%.com/|^youtube%.com/|^youtu%.be/|^%w+%.twitch%.tv/|^twitch%.tv/
# all_formats=yes
# force_all_formats=yes
# thumbnails=best
# use_manifests=yes
ytdl_path=yt-dlp
